name: Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_OPEDROMARTINS }}
    - name: Build the Docker image
      run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}/pointcloud_labeler:latest Docker
    - name: Push the image to Docker Hub
      run: |
          DATE=$(date +"%d%b%Y-%H-%M")
          docker tag ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}/pointcloud_labeler:latest ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}/pointcloud_labeler:$DATE

          docker push ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}/pointcloud_labeler:$DATE
          docker push ${{ secrets.DOCKER_HUB_USERNAME_OPEDROMARTINS }}/pointcloud_labeler:latest